peripteras/kiosks/urls.py
from django.conf.urls import include, patterns, url


urlpatterns = patterns(
    'peripteras.kiosks',


    # View kiosk dashboard
    url('^kiosk/dashboard/', 'views.kiosk', name='kiosk_dashboard'),

    # Kiosk info page
    url('^kiosk/info', 'views.kiosk_info', name='kiosk_info'),

    # View kiosk help
    url('^kiosk/help/', 'views.help', name='help'),

    # View order
    url('^kiosk/view/order/(?P<order_id>[\d]+)',
        'views.order', name='view_order'),

    # Ficnish order
    url('^kiosk/order/(?P<order_id>[\d]+)/complete',
        'views.complete_order', name='complete_order'),

    # Ficnish order
    url('^kiosk/items/all', 'views.all_items', name='all_items'),

    # Edit an item
    url('^kiosk/item/(?P<item_id>[\d]+)/edit',
        'views.item_edit', name='item_edit'),

    # Add an item
    url('^kiosk/item/add', 'views.item_add', name='item_add'),

    # Delete an item
    url('^kiosk/item/(?P<item_id>[\d]+)/delete',
        'views.item_delete', name='item_delete'),

    # upload_list
    url('^kiosk/item/upload', 'views.upload_list', name='upload_list'),


)

peripteras/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url, handler400, handler403, handler404, handler500

from django.contrib import admin

from peripteras.sitemaps import KioskSitemap

sitemaps = {
    'kiosks': KioskSitemap
}


admin.site.site_header = 'Super root panel'
admin.site.site_title = 'Super root'

urlpatterns = patterns(
    '',
    url(r'', include('peripteras.public.urls', 'public')),

    url(r'', include('peripteras.users.urls', 'users')),

    url(r'', include('peripteras.kiosks.urls', 'managers')),

    # API URL
    url(r'^api/', include('peripteras.public.api.urls')),

    # User API URL
    url(r'^user/api/', include('peripteras.users.api.urls')),

    # Kiosk managers API URL
    url(r'^managers/api/', include('peripteras.kiosks.api.urls')),

    # sitemap and robots
    url(r'^sitemap.xml$', 'django.contrib.sitemaps.views.sitemap',
        {'sitemaps': sitemaps}),
    # url(r'^robots.txt$', include('robots.urls')),


    # API URL
    # url(r'^api/', include('peripteras.public.api.urls')),

    # Admin URLs
    url(r'^admin/', include(admin.site.urls)),

    # SimpleUsers URLs
    # url(r'^user/', include('peripteras.users.urls', 'user')),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT})

)

peripteras/users/api/urls.py
from django.conf.urls import patterns, url, include

from rest_framework.routers import DefaultRouter

from peripteras.users.api.views import AddToBasket, GetFromBasket, RemoveFromBasket

router = DefaultRouter()

urlpatterns = patterns(
    '',
    url(r'^basket/get/$', GetFromBasket.as_view(), name='basket_get'),
    url(r'^basket/add/$', AddToBasket.as_view(), name='basket_add'),
    url(r'^basket/remove/$', RemoveFromBasket.as_view(), name='basket_get'),

)

peripteras/users/urls.py
from django.conf.urls import include, patterns, url
from django.contrib.auth import views as auth_views

from peripteras.users.forms import LoginAuthenticationForm


urlpatterns = patterns(
    'peripteras.users',

    # Private area "/user" is difined at main urls.py
    # url(r'^login/$',
    #     auth_views.login,
    #     {'template_name': 'users/login.html',
    #      'authentication_form': LoginAuthenticationForm},
    #     name='auth_login'),
    # url(r'^password/change/$',
    #     'views.password_change',
    #     name='password_change'),
    
    # Register new user
    # url('^register/$', 'views.register', name='register'),

    # Non django style for user login
    # url('^login/$', 'views.custom_login', name='custom_login'),

    url(r'^login/$',
        auth_views.login,
        {'template_name': 'users/login.html',
         'authentication_form': LoginAuthenticationForm},
        name='auth_login'),

    # Register users
    url('^register/$', 'views.register', name='register'),

    # Register manager
    url('^manager/register$', 'views.register_manager', name='register_manager'),

    # Logout user
    url(r'^logout/$',
        auth_views.logout,  {'next_page': '/'}, name='logout'),

    #View Basket
    url('^basket/(?P<kiosk_id>[\d]+)/', 'views.basket', name='basket'),

    #View complete info
    url('^order/(?P<kiosk_id>[\d]+)/completed/', 'views.completed', name='order_completed'),

    #View Basket
    url('^feedback/(?P<order_id>[\d]+)/add', 'views.add_feedback', name='add_feedback'),



)

peripteras/kiosks/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import datetime
import os
import uuid

from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError

from django.contrib.auth.models import User
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from sorl.thumbnail import ImageField, get_thumbnail
from uuslug import uuslug as slugify

GENDER_CHOICES = (
    (True, 'Female'),
    (False, 'Male'),
)


def _validate_birth_date(data, **kwargs):
    """Validator to ensure age of at least 18 years old."""
    today = timezone.now().date()
    youth_threshold_day = (datetime.date(today.year - 18, today.month,
                                         today.day) +
                           datetime.timedelta(hours=24))
    if data > youth_threshold_day:
        raise ValidationError('Provided Birthdate is not valid.')
        return "N/A"

    return data


def _get_upload_path(instance, filename):
    return os.path.join(settings.ITEM_LOGO_DIR,
                        str(uuid.uuid4()) + '.jpg')


class KioskManager(models.Model):
    user = models.OneToOneField(User)

    kiosk = models.ForeignKey('kiosks.Kiosk', null=True, blank=True)

    birth_date = models.DateField(validators=[_validate_birth_date],
                                  blank=False, null=True,
                                  help_text="Manager's birth date")

    mobile_number = models.CharField(
        max_length=40, blank=True,
        verbose_name=_(u'Mobile Number'),
        validators=[
            RegexValidator(regex=r'("")|(^[0-9+]+$)',
                           message='Please only numbers and "+".')])

    email = models.EmailField(blank=True, null=True,
                              help_text="Kiosk Manager's contact emal.")

    def __unicode__(self):
        # return "Kiosk manager: id {0}".format(self.id)
        return u'Manager for: {0}'.format(self.kiosk)


class Kiosk(models.Model):

    title = models.CharField(max_length=60, blank=True, null=True,
                             help_text=_(u'Kiosk title'))

    street = models.CharField(max_length=60, blank=False, null=True,
                              help_text=_(u'Street'))

    number = models.IntegerField(null=True)

    region = models.CharField(max_length=60, blank=True, null=True,
                              help_text=_(u'Region'))

    tk = models.IntegerField(null=True)

    city = models.CharField(max_length=60, blank=True, null=True,
                            help_text=_(u'City'))

    activated = models.BooleanField(
        default=False, blank=True, verbose_name=_(u'Activate kiosk or not'))

    phone_number = models.CharField(
        max_length=40, blank=True,
        verbose_name=_(u'Phone Number'),
        validators=[
            RegexValidator(regex=r'("")|(^[0-9+]+$)',
                           message='Please only numbers and "+".')])

    info = models.CharField(max_length=400, blank=True, null=True,
                            help_text=_(u'Kiosk info'))

    max_distance = models.IntegerField(null=True, blank=True, default=1)

    created_on = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True, null=True)

    image = ImageField(null=True, blank=True, upload_to=_get_upload_path)

    delivery_fee = models.DecimalField(
        max_digits=6, decimal_places=2, blank=False, default=0)

    is_open = models.BooleanField(
        default=True, blank=True, verbose_name=_(u'Is kiosk open or not'))

    def get_image_thumbnail(self, geometry=settings.AVATAR_DIMENSIONS, **kwargs):
        if 'crop' not in kwargs:
            kwargs['crop'] = 'center'
        if self.image:
            return get_thumbnail(self.image, geometry, **kwargs)
        return get_thumbnail(settings.DEFAULT_LOGO_PATH, geometry, **kwargs)

    def get_image_url(self, geometry=settings.KIOSK_DIMENSIONS, **kwargs):
        return self.get_image_thumbnail(geometry, **kwargs).url

    def __unicode__(self):
        # return '{0},{1},{2}'.format(self.street, self.number, self.city)
        return unicode('Kiosk id: {0}'.format(self.id))


class Item(models.Model):

    kiosk = models.ForeignKey('kiosks.Kiosk')

    price = models.DecimalField(max_digits=6, decimal_places=2, blank=False)

    brand = models.ForeignKey('kiosks.Brand', blank=False)

    title = models.CharField(max_length=255, default='', blank=False,
                                                     verbose_name=_(u'Item title'))

    slug = models.SlugField(unique=True, blank=True, max_length=255)

    category = models.ForeignKey('kiosks.Category')

    created_on = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True, null=True)

    image = ImageField(default='', blank=True, upload_to=_get_upload_path)

    online_offer = models.NullBooleanField(
        default=False, blank=False, verbose_name=_(u'Online offer'))

    # online_offer = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title, instance=self)
        super(Item, self).save(*args, **kwargs)

    def is_offer(self):
        if self.online_offer:
            return (u'Ναι')
        return (u'Όχι')

    def get_item_name(self):
        return (u'{0}'.format(self.title))

    def __unicode__(self):
        return 'Item id: {0}'.format(self.id)


class Category(models.Model):
    title = models.CharField(max_length=255, default='', blank=False,
                                                     verbose_name=_(u'Category title'))

    slug = models.SlugField(unique=True, blank=True, max_length=255)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title, instance=self)
        super(Category, self).save(*args, **kwargs)

    def __unicode__(self):
        return (u'{0}'.format(self.title))

    class Meta:
        verbose_name_plural = "Categories"


class Brand(models.Model):
    title = models.CharField(max_length=255, default='', blank=False,
                                                     verbose_name=_(u'Brand name'))

    def __unicode__(self):
        return (u'{0}'.format(self.title))


class Support(models.Model):
    kiosk = models.ForeignKey('kiosks.Kiosk', null=True, blank=False)

    manager = models.ForeignKey('kiosks.KioskManager', null=True, blank=False)

    subject = models.CharField(max_length=100, default='', blank=False,
                               verbose_name=_(u'Subject'))

    text = models.TextField(default='', blank=True,
                            verbose_name=_(u'Comments'))

    def __unicode__(self):
        return unicode('{0}'.format(self.subject))

peripteras/users/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import datetime
import os
import uuid

from django.core.validators import RegexValidator
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone

from peripteras.kiosks.models import KioskManager


class SimpleUser(models.Model):
    """
    Definition of SimpleUser Model. This model extends the default
    Django User model with one to one field
    """

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    first_name = models.CharField(max_length=60, blank=True, null=True,
                                  help_text=_(u'First name'))

    last_name = models.CharField(max_length=60, blank=True, null=True,
                                 help_text=_(u'Last name'))

    mobile_number = models.CharField(
        max_length=40, blank=True, null=True,
        verbose_name=_(u'Mobile Number'),
        validators=[
            RegexValidator(regex=r'("")|(^[0-9+]+$)',
                           message='Please only numbers and "+".')])

    addresses = models.ForeignKey('users.Addresses', blank=True, null=True)

    orders = models.ManyToManyField('users.Order', related_name='orders', blank=True, null=True)

    # avatar = ImageField(default='', blank=True, upload_to=_get_upload_path)

    created_on = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return "Simple UserID: {0}".format(self.id)

    def get_full_name(self):
        return _(u'{0} {1}'.format(self.first_name, self.last_name))


class Addresses(models.Model):

    street = models.CharField(max_length=60, blank=False, null=True,
                              help_text=_(u'Street'))

    number = models.IntegerField()

    city = models.CharField(max_length=60, blank=False, null=True,
                            help_text=_(u'City'))

    region = models.CharField(max_length=60, blank=False, null=True,
                              help_text=_(u'Region'))

    tk = models.IntegerField()

    simple_user_id = models.IntegerField(blank=False, null=True,
                                         help_text=_(u'simple_user id'))

    class Meta:
        verbose_name_plural = "Addresses"

    def __unicode__(self):
        # return self.street + " " + str(self.number)
        # return "{0} {1} ({2}), {3}".format(self.street, self.number,
        # self.region, self.city)
        return "Address id: {0}".format(self.id)


class Order(models.Model):

    simple_user = models.ForeignKey(
        'users.SimpleUser', blank=False, null=False)

    first_name = models.CharField(max_length=60, blank=True, null=True,
                                  help_text=_(u'First name'))

    last_name = models.CharField(max_length=60, blank=True, null=True,
                                 help_text=_(u'Last name'))

    mobile_number = models.CharField(
        max_length=40, blank=True, null=True,
        verbose_name=_(u'Mobile Number'),
        validators=[
            RegexValidator(regex=r'("")|(^[0-9+]+$)',
                           message='Please only numbers and "+".')])

    address = models.ForeignKey('users.Addresses', blank=False, null=False)

    basket_items = models.ManyToManyField(
        'kiosks.Item', related_name='items', blank=True)
    # ord.basket_items.all()
    # ord.basket_items.add(itm)

    basket_items_ids = models.TextField(null=True)

    completed = models.NullBooleanField(
        default=False, blank=True, verbose_name=_(u'Completed order'))

    created_on = models.DateTimeField(auto_now_add=True)

    closed_on = models.DateTimeField(blank=True, null=True)

    kiosk = models.ForeignKey('kiosks.Kiosk', blank=False, null=True)

    total_sum = models.DecimalField(
        max_digits=6, decimal_places=2, blank=False, null=True)

    comments = models.TextField(default='', blank=True,
                                verbose_name=_(u'Comments'))

    def full_name(self):
        return _(u'{0} {1}'.format(self.first_name, self.last_name))

    def __unicode__(self):
        return "Order id: {0}".format(self.id)


def is_manager(self):
    try:
        manager = KioskManager.objects.get(user__id=self.id)
    except KioskManager.DoesNotExist:
        manager = False

    return manager

User.add_to_class("is_manager", is_manager)


class Feedback(models.Model):
    simple_user = models.ForeignKey(SimpleUser, null=False, blank=False)

    order = models.ForeignKey(Order, null=False, blank=False)

    stars = models.IntegerField()

    text = models.TextField(default='', blank=True,
                            verbose_name=_(u'Feedback text'))

    created_on = models.DateTimeField(auto_now_add=True, null=True)

    class Meta:
        unique_together = ('simple_user', 'order',)

    def __unicode__(self):
        return u'Feedback id: {0}'.format(self.id)

peripteras/templates/jinja2/users/add_feedback.html
{% extends "base.html" %}
{% block css_files %}
<link href="{{ static('css/users/complete.css') }}" rel="stylesheet">

{%endblock%}

{% block page_title %}Feedback e-peripteras online delivery περιπτέρου{% endblock %}

{% block meta_description %}online delivery{% endblock %}
{% block keywords %}delivery, περίπτερο{% endblock %}


{% block site_css %}
<link href="{{ static('css/jquery-ui.min.css') }}" rel="stylesheet" type="text/css">
<link href="{{ static('css/rating.css') }}" rel="stylesheet" type="text/css">
{% endblock %}


{% block content %}
<div id="msg"></div>
<input type="hidden" name="kiosk_id" id="kiosk_id" value="{{order.kiosk.id}}">
<div class="container wrp">
	<br>

	<div class="row" >
		<div class="col-lg-12 text-center ">
			<h3>Αφήστε αξιολόγηση για {{order.kiosk.title}}</h3>
		</div>
	</div>
	<br><br>
	<div class="row" >
		<div class="col-lg-6 text-center col-lg-offset-3">

			<form method="post" action="{{ url('users:add_feedback', args=[order.id]) }}" role="form" enctype="multipart/form-data">
				<input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
				<p class="text-left">Πόσο σας ικανοποίησε το περίπτερο <i>1 έως 10</i></p>
				<div id="star-rating">
				    <input type="radio" name="stars" class="rating" value="1" />
				    <input type="radio" name="stars" class="rating" value="2" />
				    <input type="radio" name="stars" class="rating" value="3" />
				    <input type="radio" name="stars" class="rating" value="4" />
				    <input type="radio" name="stars" class="rating" value="5" />
				    <input type="radio" name="stars" class="rating" value="6" />
				    <input type="radio" name="stars" class="rating" value="7" />
				    <input type="radio" name="stars" class="rating" value="8" />
				    <input type="radio" name="stars" class="rating" value="9" />
				    <input type="radio" name="stars" class="rating" value="10" />
				</div>
				<hr>

				<textarea class="form-control input-md" cols="40" id="id_comments" name="text" placeholder="Πείτε μας την γνώμη σας" rows="5"></textarea>

				<hr>
				<div class="form-group">
					<button type="submit" class="btn btn-success">Προσθήκη</button>
				</div>
			</form>

		</div>		
	</div>	

</div>

{% endblock %}

{% block site_js %}
	<script src="{{ static('js/libs/jquery-ui.min.js') }}"></script>
	<script src="{{ static('js/libs/rating.js') }}"></script>
	<script type="text/javascript">

		$(document).ready(function(){

			$('#star-rating').rating(function(vote, event){
			});	

		});
	</script>


{% endblock %}

peripteras/templates/jinja2/users/feedback_success.html
{% extends "base.html" %}
{% block css_files %}
<link href="{{ static('css/public/login.css') }}" rel="stylesheet">

{%endblock%}

{% block page_title %}{{title}} e-peripteras online delivery περιπτέρου{% endblock %}

{% block meta_description %}online delivery{% endblock %}
{% block keywords %}delivery, περίπτερο{% endblock %}


{% block site_css %}
<style type="text/css">
	body {
		background:url('/static/img/bg.jpg') no-repeat center center fixed;
	}
</style>
{% endblock %}


{% block content %}
<div class="container wrp">
	<div class="row" >
		<br><br><br><br>
		<div class="col-lg-6 col-md-6 col-lg-offset-3 col-md-offset-3 text-center">
			<div class="alert alert-success">
				{{msg}} 
			</div>

			<a href="{{ url('public:kiosk', args=[kiosk.id]) }}" class="btn btn-block order-btn">Επιστροφή</a>

			
		</div>

	</div>

	
</div>

{% endblock %}

{% block site_js %}
	<script type="text/javascript">

		$(document).ready(function(){			

		});
	</script>
{% endblock %}

peripteras/templates/jinja2/users/register-manager.html
{% extends "base.html" %}
{% block css_files %}
<link href="{{ static('css/public/register-manager.css') }}" rel="stylesheet">
<link href="{{ static('css/jquery-ui.min.css') }}" rel="stylesheet" type="text/css">

{%endblock%}

{% block page_title %}Εγγραφή περιπτερά e-peripteras online delivery περιπτέρου{% endblock %}

{% block meta_description %}online delivery{% endblock %}
{% block keywords %}delivery, περίπτερο{% endblock %}


{% block site_css %}
<style type="text/css">
	body {
		background:url('/static/img/bg.jpg') no-repeat center center fixed;
	}
</style>
{% endblock %}


{% block content %}
<div class="container wrp">
	<div class="row" >
		<div class="col-lg-12 col-md-12">
			<div class="row">
				<div class="col-lg-6 left-col">
					<h3 class="text-center bold">Εγγραφη περιπτέρου</h3>
					<h5 class="text-center bold">Στοιχεία διαχειριστή</h5>
					<form method="post" id="registerForm" action="{{ url('users:register_manager')}}" role="form" enctype="multipart/form-data">
						<input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">

						<div class="form-group">	
							<input class="form-control input-lg" name="first_name" placeholder="Όνομα" required="True" type="text">
							{% if user_form %}
							{% if user_form.first_name.errors%}
							<div class="alert alert-danger">
								{{user_form.first_name.errors}}
							</div>
							{% endif %}
							{% endif %}
						</div>

						<div class="form-group">	
							<input class="form-control input-lg" name="last_name" placeholder="Επίθετο" required="True" type="text">
							{% if user_form %}
							{% if user_form.last_name.errors%}
							<div class="alert alert-danger">
								{{user_form.last_name.errors}}
							</div>
							{% endif %}
							{% endif %}
						</div>

						<div class="form-group">	
							<input class="form-control input-lg" name="username" placeholder="Username" required="True" type="text">
							{% if user_form %}
							{% if user_form.username.errors%}
							<div class="alert alert-danger">
								{{user_form.username.errors}}
							</div>
							{% endif %}
							{% endif %}
						</div>

						<div class="form-group">
							<input class="form-control input-lg" name="email" placeholder="Email" required="True" type="email">
							{% if user_form %}
							{% if user_form.email.errors%}
							<div class="alert alert-danger">
								{{user_form.email.errors}}
							</div>
							{% endif %}
							{% endif %}
						</div>

						<div class="form-group">
							<input class="form-control input-lg" id='id_birth_date' name="birth_date" placeholder="Ημερομηνία γέννησης" required="True" type="date">
							{% if manager_form.birth_date.errors%}
							<div class="alert alert-danger">
								{{manager_form.birth_date.errors}}
							</div>
							{% endif %}
						</div>

						<div class="form-group">
							<input class="form-control input-lg" name="mobile_number" placeholder="Τηλέφωνο επικοινωνίας" required="True" type="text">
							{% if manager_form.mobile_number.errors%}
							<div class="alert alert-danger">
								{{manager_form.mobile_number.errors}}
							</div>
							{% endif %}
						</div>


						<div class="form-group">
							<input class="form-control input-lg" name="password" placeholder="Κωδικός" required="True" type="password">
							{% if user_form %}
							{% if user_form.password.errors%}
							<div class="alert alert-danger">
								{{user_form.password.errors}}
							</div>
							{% endif %}
							{% endif %}
						</div>
						
						<div class="form-group">
							<input class="form-control input-lg" name="password2" placeholder="Επανάληψη κωδικού" required="True" type="password">
							{% if user_form %}
							{% if user_form.password2.errors%}
							<div class="alert alert-danger">
								{{user_form.password2.errors}}
							</div>
							{% endif %}
							{% endif %}
						</div>
						<hr>
						<h5 class="text-center bold">Στοιχεία περιπτέρου / mini-market</h5>
						<div class="form-group">
							<input class="form-control input-lg" name="title" placeholder="Επωνυμία" required="True" type="text">
							{% if kiosk_form.title.errors%}
							<div class="alert alert-danger">
								{{kiosk_form.title.errors}}
							</div>
							{% endif %}
						</div>
						<div class="form-group">
							<input class="form-control input-lg" name="street" placeholder="Οδός" required="True" type="text">
							{% if kiosk_form.street.errors%}
							<div class="alert alert-danger">
								{{kiosk_form.street.errors}}
							</div>
							{% endif %}
						</div>

						<div class="form-group">
							<input class="form-control input-lg" name="number" placeholder="Αριθμός" required="True" type="text">
							{% if kiosk_form.number.errors%}
							<div class="alert alert-danger">
								{{kiosk_form.number.errors}}
							</div>
							{% endif %}
						</div>

						<div class="form-group">
							<input class="form-control input-lg" name="city" placeholder="Πόλη" required="True" type="text">
							{% if kiosk_form.city.errors%}
							<div class="alert alert-danger">
								{{kiosk_form.city.errors}}
							</div>
							{% endif %}
						</div>

						<div class="form-group">
							<input class="form-control input-lg" name="tk" placeholder="Ταχ.Κώδικας" required="True" type="text">
							{% if kiosk_form.tk.errors%}
							<div class="alert alert-danger">
								{{kiosk_form.tk.errors}}
							</div>
							{% endif %}
						</div>

						<div class="form-group text-center">
							<label class="checkbox-inline">Αποδέχομαι τους <a href="{{ url('public:terms') }}">όρους χρήσης</a></label>
							<input type="checkbox" required style="vertical-align: bottom;">
							
						</div>

						<button class="btn btn-success btn-block" id="register-btn" type="submit">Εγγραφή</button>
					</form>
					<br><br><br><br><br>
				</div>




				<div class="col-lg-6 left-col text-justify">
					<h3 class="text-center bold">Έχεις περίπτερο;</h3>

					Τώρα το περίπτερό σου μπορεί να είναι προσβάσιμο μέσω του e-peripteras.gr , δίνοντάς σου τη δυνατότητα να δέχεσαι παραγγελίες μέσω internet, και επιτρέποντας σου να παίρνεις  παραγγελίες από χιλιάδες κόσμο από όποιες περιοχές έχεις εσύ διαλέξει. <br><hr>

					<ul>
						<li>&#9679;  Εντελώς δωρεάν.</li>
						<li>&#9679;  24 ώρες το 24ωρο.</li>
						<li>&#9679;  Χωρίς extra χρέωση στο περίπτερο σου η τον πελάτη.</li>
						<li>&#9679;  Διαλέγεις εσύ τα προϊόντα που θες να βάλεις.</li>
						<li>&#9679;  Εύκολα και γρήγορα.</li>
					</ul><br>
					Το e-peripteras.gr σου παρέχει έτοιμη λίστα προϊόντων, μέσα απ την οποία διαλέγεις τα προϊόντα που θέλεις με την ανάλογη τιμή της επιλογής σου. <br>
					Κάνε εγγραφή τώρα και δώσε την δυνατότητα σε όλο τον κόσμο να δει το περίπτερο σου.

					<br><br><br><br><br>
				</div>
			</div>
		</div>
	</div>

	
</div>

{% endblock %}

{% block site_js %}
<script src="{{ static('js/libs/jquery-ui.min.js') }}"></script>
<script src="{{ static('js/libs/jquery.ui.datepicker-it.js') }}"></script>
<script type="text/javascript">

	$(document).ready(function() {
 
			$( "#id_birth_date" ).datepicker({
				dateFormat: 'yy-mm-dd',
				changeMonth: true,
				changeYear: true,
				yearRange: "-80:+0",
			});

		});
</script>
{% endblock %}