peripteras/kiosks/urls.py
from django.conf.urls import include, patterns, url


urlpatterns = patterns(
    'peripteras.kiosks',


    # View kiosk dashboard
    url('^kiosk/dashboard/', 'views.kiosk', name='kiosk_dashboard'),

    # Kiosk info page
    url('^kiosk/info', 'views.kiosk_info', name='kiosk_info'),

    # View kiosk help
    url('^kiosk/help/', 'views.help', name='help'),

    # View order
    url('^kiosk/view/order/(?P<order_id>[\d]+)',
        'views.order', name='view_order'),

    # Ficnish order
    url('^kiosk/order/(?P<order_id>[\d]+)/complete',
        'views.complete_order', name='complete_order'),

    # Ficnish order
    url('^kiosk/items/all', 'views.all_items', name='all_items'),

    # Edit an item
    url('^kiosk/item/(?P<item_id>[\d]+)/edit',
        'views.item_edit', name='item_edit'),

    # Add an item
    url('^kiosk/item/add', 'views.item_add', name='item_add'),

    # Delete an item
    url('^kiosk/item/(?P<item_id>[\d]+)/delete',
        'views.item_delete', name='item_delete'),

    # upload_list
    url('^kiosk/item/upload', 'views.upload_list', name='upload_list'),


)

peripteras/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url, handler400, handler403, handler404, handler500

from django.contrib import admin

from peripteras.sitemaps import KioskSitemap

sitemaps = {
    'kiosks': KioskSitemap
}


admin.site.site_header = 'Super root panel'
admin.site.site_title = 'Super root'

urlpatterns = patterns(
    '',
    url(r'', include('peripteras.public.urls', 'public')),

    url(r'', include('peripteras.users.urls', 'users')),

    url(r'', include('peripteras.kiosks.urls', 'managers')),

    # API URL
    url(r'^api/', include('peripteras.public.api.urls')),

    # User API URL
    url(r'^user/api/', include('peripteras.users.api.urls')),

    # Kiosk managers API URL
    url(r'^managers/api/', include('peripteras.kiosks.api.urls')),

    # sitemap and robots
    url(r'^sitemap.xml$', 'django.contrib.sitemaps.views.sitemap',
        {'sitemaps': sitemaps}),
    # url(r'^robots.txt$', include('robots.urls')),


    # API URL
    # url(r'^api/', include('peripteras.public.api.urls')),

    # Admin URLs
    url(r'^admin/', include(admin.site.urls)),

    # SimpleUsers URLs
    # url(r'^user/', include('peripteras.users.urls', 'user')),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT})

)

peripteras/users/api/urls.py
from django.conf.urls import patterns, url, include

from rest_framework.routers import DefaultRouter

from peripteras.users.api.views import AddToBasket, GetFromBasket, RemoveFromBasket

router = DefaultRouter()

urlpatterns = patterns(
    '',
    url(r'^basket/get/$', GetFromBasket.as_view(), name='basket_get'),
    url(r'^basket/add/$', AddToBasket.as_view(), name='basket_add'),
    url(r'^basket/remove/$', RemoveFromBasket.as_view(), name='basket_get'),

)

peripteras/users/urls.py
from django.conf.urls import include, patterns, url
from django.contrib.auth import views as auth_views

from peripteras.users.forms import LoginAuthenticationForm


urlpatterns = patterns(
    'peripteras.users',

    # Private area "/user" is difined at main urls.py
    # url(r'^login/$',
    #     auth_views.login,
    #     {'template_name': 'users/login.html',
    #      'authentication_form': LoginAuthenticationForm},
    #     name='auth_login'),
    # url(r'^password/change/$',
    #     'views.password_change',
    #     name='password_change'),
    
    # Register new user
    # url('^register/$', 'views.register', name='register'),

    # Non django style for user login
    # url('^login/$', 'views.custom_login', name='custom_login'),

    url(r'^login/$',
        auth_views.login,
        {'template_name': 'users/login.html',
         'authentication_form': LoginAuthenticationForm},
        name='auth_login'),

    # Register users
    url('^register/$', 'views.register', name='register'),

    # Register manager
    url('^manager/register$', 'views.register_manager', name='register_manager'),

    # Logout user
    url(r'^logout/$',
        auth_views.logout,  {'next_page': '/'}, name='logout'),

    #View Basket
    url('^basket/(?P<kiosk_id>[\d]+)/', 'views.basket', name='basket'),

    #View complete info
    url('^order/(?P<kiosk_id>[\d]+)/completed/', 'views.completed', name='order_completed'),

    #View Basket
    url('^feedback/(?P<order_id>[\d]+)/add', 'views.add_feedback', name='add_feedback'),



)

peripteras/kiosks/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import datetime
import os
import uuid

from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError

from django.contrib.auth.models import User
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from sorl.thumbnail import ImageField, get_thumbnail
from uuslug import uuslug as slugify

GENDER_CHOICES = (
    (True, 'Female'),
    (False, 'Male'),
)


def _validate_birth_date(data, **kwargs):
    """Validator to ensure age of at least 18 years old."""
    today = timezone.now().date()
    youth_threshold_day = (datetime.date(today.year - 18, today.month,
                                         today.day) +
                           datetime.timedelta(hours=24))
    if data > youth_threshold_day:
        raise ValidationError('Provided Birthdate is not valid.')
        return "N/A"

    return data


def _get_upload_path(instance, filename):
    return os.path.join(settings.ITEM_LOGO_DIR,
                        str(uuid.uuid4()) + '.jpg')


class KioskManager(models.Model):
    user = models.OneToOneField(User)

    kiosk = models.ForeignKey('kiosks.Kiosk', null=True, blank=True)

    birth_date = models.DateField(validators=[_validate_birth_date],
                                  blank=False, null=True,
                                  help_text="Manager's birth date")

    mobile_number = models.CharField(
        max_length=40, blank=True,
        verbose_name=_(u'Mobile Number'),
        validators=[
            RegexValidator(regex=r'("")|(^[0-9+]+$)',
                           message='Please only numbers and "+".')])

    email = models.EmailField(blank=True, null=True,
                              help_text="Kiosk Manager's contact emal.")

    def __unicode__(self):
        # return "Kiosk manager: id {0}".format(self.id)
        return u'Manager for: {0}'.format(self.kiosk)


class Kiosk(models.Model):

    title = models.CharField(max_length=60, blank=True, null=True,
                             help_text=_(u'Kiosk title'))

    street = models.CharField(max_length=60, blank=False, null=True,
                              help_text=_(u'Street'))

    number = models.IntegerField(null=True)

    region = models.CharField(max_length=60, blank=True, null=True,
                              help_text=_(u'Region'))

    tk = models.IntegerField(null=True)

    city = models.CharField(max_length=60, blank=True, null=True,
                            help_text=_(u'City'))

    activated = models.BooleanField(
        default=False, blank=True, verbose_name=_(u'Activate kiosk or not'))

    phone_number = models.CharField(
        max_length=40, blank=True,
        verbose_name=_(u'Phone Number'),
        validators=[
            RegexValidator(regex=r'("")|(^[0-9+]+$)',
                           message='Please only numbers and "+".')])

    info = models.CharField(max_length=400, blank=True, null=True,
                            help_text=_(u'Kiosk info'))

    max_distance = models.IntegerField(null=True, blank=True, default=1)

    created_on = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True, null=True)

    image = ImageField(null=True, blank=True, upload_to=_get_upload_path)

    delivery_fee = models.DecimalField(
        max_digits=6, decimal_places=2, blank=False, default=0)

    is_open = models.BooleanField(
        default=True, blank=True, verbose_name=_(u'Is kiosk open or not'))

    def get_image_thumbnail(self, geometry=settings.AVATAR_DIMENSIONS, **kwargs):
        if 'crop' not in kwargs:
            kwargs['crop'] = 'center'
        if self.image:
            return get_thumbnail(self.image, geometry, **kwargs)
        return get_thumbnail(settings.DEFAULT_LOGO_PATH, geometry, **kwargs)

    def get_image_url(self, geometry=settings.KIOSK_DIMENSIONS, **kwargs):
        return self.get_image_thumbnail(geometry, **kwargs).url

    def __unicode__(self):
        # return '{0},{1},{2}'.format(self.street, self.number, self.city)
        return unicode('Kiosk id: {0}'.format(self.id))


class Item(models.Model):

    kiosk = models.ForeignKey('kiosks.Kiosk')

    price = models.DecimalField(max_digits=6, decimal_places=2, blank=False)

    brand = models.ForeignKey('kiosks.Brand', blank=False)

    title = models.CharField(max_length=255, default='', blank=False,
                                                     verbose_name=_(u'Item title'))

    slug = models.SlugField(unique=True, blank=True, max_length=255)

    category = models.ForeignKey('kiosks.Category')

    created_on = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True, null=True)

    image = ImageField(default='', blank=True, upload_to=_get_upload_path)

    online_offer = models.NullBooleanField(
        default=False, blank=False, verbose_name=_(u'Online offer'))

    # online_offer = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title, instance=self)
        super(Item, self).save(*args, **kwargs)

    def is_offer(self):
        if self.online_offer:
            return (u'Ναι')
        return (u'Όχι')

    def get_item_name(self):
        return (u'{0}'.format(self.title))

    def __unicode__(self):
        return 'Item id: {0}'.format(self.id)


class Category(models.Model):
    title = models.CharField(max_length=255, default='', blank=False,
                                                     verbose_name=_(u'Category title'))

    slug = models.SlugField(unique=True, blank=True, max_length=255)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title, instance=self)
        super(Category, self).save(*args, **kwargs)

    def __unicode__(self):
        return (u'{0}'.format(self.title))

    class Meta:
        verbose_name_plural = "Categories"


class Brand(models.Model):
    title = models.CharField(max_length=255, default='', blank=False,
                                                     verbose_name=_(u'Brand name'))

    def __unicode__(self):
        return (u'{0}'.format(self.title))


class Support(models.Model):
    kiosk = models.ForeignKey('kiosks.Kiosk', null=True, blank=False)

    manager = models.ForeignKey('kiosks.KioskManager', null=True, blank=False)

    subject = models.CharField(max_length=100, default='', blank=False,
                               verbose_name=_(u'Subject'))

    text = models.TextField(default='', blank=True,
                            verbose_name=_(u'Comments'))

    def __unicode__(self):
        return unicode('{0}'.format(self.subject))

peripteras/kiosks/api/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*- 
import re

from collections import Counter

from django.conf import settings
from django.core.exceptions import SuspiciousOperation
from django.http import Http404, HttpResponseForbidden
from django.shortcuts import get_object_or_404
from django.db.models import Q, FieldDoesNotExist


from rest_framework.authentication import SessionAuthentication
from rest_framework.decorators import detail_route
from rest_framework.permissions import IsAuthenticated, IsAdminUser
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import generics, status, mixins, viewsets

from peripteras.kiosks.models import Kiosk, Item
from peripteras.public.api.serializers import KioskSerializer, ItemkSerializer
from peripteras.kiosks.api.serializers import OrderSerializer

from peripteras.common.mixins import FilterMixin

from peripteras.users.models import Order

from peripteras.kiosks.models import KioskManager

		

class GetAllOrders(FilterMixin,generics.CreateAPIView):
	"""
	Endpoint for fetching the basket
	http://localhost:8001/user/api/basket/get/
	"""


	authentication_classes = (SessionAuthentication, )
	permission_classes = (IsAuthenticated, )
	# queryset = Item.objects.all()

	filter_fields = (
		'kiosk_id'
	)


	serializer_class = OrderSerializer

	def get(self, request):
		
		kiosk_id = request.GET.get("kiosk_id", None)

		try:
			kiosk = Kiosk.objects.get(id=kiosk_id, kioskmanager__user=request.user)
		except Kiosk.DoesNotExist:

			data={
				'error':'403 FORBIDDEN',
				'msg': 'No cheats...' 
			}
			return Response(data, status=status.HTTP_403_FORBIDDEN)
		   
		


		orders = Order.objects.filter(kiosk=kiosk_id, completed=False).order_by('created_on')
			
		orders = self.apply_filters(request, orders)

		serializer = self.serializer_class(orders, many=True)

		return Response(serializer.data, status=status.HTTP_200_OK)

peripteras/templates/jinja2/kiosk-managers/finished.html
{% extends "manager_base.html" %}

{% block menu_conttent %}
	<li><a href="{{ url('managers:kiosk_dashboard') }}">Παραγγελίες <span class="sr-only">(current)</span></a></li>
	<li><a href="{{ url('managers:kiosk_info') }}"">Πληροφορίες περιπτέρου</a></li>
	<li><a href="{{ url('managers:all_items') }}">Προϊόντα</a></li>
	<li><a href="{{ url('managers:help') }}">Βοήθεια</a></li>
{%endblock%}




{% block main_conttent %}
<h1 class="page-header text-center">Πληροφορίες</h1>

<div class="row" >
	<div class="col-lg-12 text-center ">
		<div class="alert alert-warning max">
			{{txt}}
		</div>
		<br>
		<a href="{{ url('managers:kiosk_dashboard') }}">Παραγγελίες</a><br><br>
		<a href="{{ url('managers:all_items') }}">Προϊόντα</a>

	</div>
</div>

{%endblock%}


{% block js_scripts %}

{% endblock %}

peripteras/templates/jinja2/kiosk-managers/help.html
{% extends "manager_base.html" %}

{% block menu_conttent %}
	<li><a href="{{ url('managers:kiosk_dashboard') }}">Παραγγελίες <span class="sr-only">(current)</span></a></li>
	<li><a href="{{ url('managers:kiosk_info') }}"">Πληροφορίες περιπτέρου</a></li>
	<li><a href="{{ url('managers:all_items') }}">Προϊόντα</a></li>
	<li class="active"><a href="{{ url('managers:help') }}">Βοήθεια</a></li>
{%endblock%}




{% block main_conttent %}
<style type="text/css">

label{
	display: none;
}
input,textarea {
	margin-bottom: : 10px;
	margin-top: 10px;
	vertical-align: middle;
}

ul{
	list-style-type: none;
	padding: 0px;
}
.errorlist{ 
	background-color: #e64d4d;
	padding: 10px;
	color: white;
	margin-top: 5px;
}
</style>
<h1 class="page-header text-center">Ζητήστε βοήθεια</h1>

<div class="row" >
	<div class="col-lg-4 col-md-4 col-sm-4  text-left ">
		<form method="post" action="." role="form" enctype="multipart/form-data">
			<input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
			{{support_form}}
			<hr>
			<div class="form-group">
				<button type="submit" class="btn btn-success">Αποστολή</button>
			</div>
		</form>
	</div>
</div>

{%endblock%}


{% block js_scripts %}

{% endblock %}

peripteras/templates/jinja2/kiosk-managers/home.html
{% extends "manager_base.html" %}

{% block menu_conttent %}
	<li class="active"><a href="{{ url('managers:kiosk_dashboard') }}">Παραγγελίες <span class="sr-only">(current)</span></a></li>
	<li><a href="{{ url('managers:kiosk_info') }}"">Πληροφορίες περιπτέρου</a></li>
	<li><a href="{{ url('managers:all_items') }}">Προϊόντα</a></li>
	<li><a href="{{ url('managers:help') }}">Βοήθεια</a></li>
{%endblock%}



{% block main_conttent %}

<input type="hidden" id='kiosk_id' value="{{kiosk.id}}">
<h1 class="page-header">Διαχειριστικό μενού παραγγελιών</h1>

<div class="row placeholders">
	<div class="col-xs-6 col-sm-3 placeholder">
		<h4>Παραγγελίες σε αναμονή</h4>
		<div class="top-label-text">{{orders.count()}}</div>
	</div>
	<!-- <div class="col-xs-6 col-sm-3 placeholder">
		<img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
		<h4>Label</h4>
		<span class="text-muted">Something else</span>
	</div>
	<div class="col-xs-6 col-sm-3 placeholder">
		<img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
		<h4>Label</h4>
		<span class="text-muted">Something else</span>
	</div>
	<div class="col-xs-6 col-sm-3 placeholder">
		<img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
		<h4>Label</h4>
		<span class="text-muted">Something else</span>
	</div> -->
</div>
{% if orders %}
<h2 class="sub-header">Παραγγελίες</h2>
<!-- <div class="table-responsive"> -->


<div class="list-group" >
	<a href="#" class="list-group-item">
		<div class="row">
			<div class="col-lg-1">
				<strong>A/A</strong>				
			</div>
			<div class="col-lg-4">
				<strong>Οδός</strong>							
			</div>
			<div class="col-lg-2">
				<strong>Όνομα</strong>
			</div>
			<div class="col-lg-3">
				<strong>Ημερομηνία</strong>
			</div>
			<div class="col-lg-1">
				<strong>Σύνολο</strong>
			</div>
		</div>
	</a>
</div>
{% else %}
<div class="alert alert-info text-center">
	Δεν υπάρχουν παραγγελίες
</div>
{% endif %}


<div id="order-ajax">

	{% raw %}
	<script id="orders-items" type="text/x-handlebars-template">
		{{#each orders}}
		<a href="/kiosk/view/order/{{orderId}}" class="list-group-item">
			<div class="row">
				<div class="col-lg-1">
					{{math @index "+" 1}}				
				</div>
				<div class="col-lg-4">
					{{street}} {{number}} {{city}}
				</div>
				<div class="col-lg-2">
					{{fullName}}
				</div>
				<div class="col-lg-3">
					{{created}}
				</div>
				<div class="col-lg-1">
					{{totalSum}}&euro;
				</div>
			</div>
		</a>
		{{/each}}
	</script>
	{% endraw %}
</div>

{%endblock%}


{% block js_scripts %}
	<script src="{{ static('js/kiosk-managers/get-orders.js') }}"></script>
{% endblock %}

peripteras/templates/jinja2/kiosk-managers/item_add.html
{% extends "manager_base.html" %}

{% block menu_conttent %}
	<li><a href="{{ url('managers:kiosk_dashboard') }}">Παραγγελίες <span class="sr-only">(current)</span></a></li>
	<li><a href="{{ url('managers:kiosk_info') }}"">Πληροφορίες περιπτέρου</a></li>
	<li><a href="{{ url('managers:all_items') }}">Προϊόντα</a></li>
	<li><a href="{{ url('managers:help') }}">Βοήθεια</a></li>
{%endblock%}




{% block main_conttent %}
<style type="text/css">

label{
	display: none;
}
input,select {
	margin-bottom: : 10px;
	margin-top: 10px;
	vertical-align: middle;
}
#id_online_offer{
	margin: 0px;
}
ul{
	list-style-type: none;
	padding: 0px;
}
.errorlist{ 
	background-color: #e64d4d;
	padding: 10px;
	color: white;
	margin-top: 5px;
}
</style>
<h1 class="page-header">Προσθήκη προϊόντος</h1>

<div class="row" >
	<div class="col-lg-4 col-md-4 col-sm-4  text-left ">
		<form method="post" action="{{ url('managers:item_add')}}" role="form" enctype="multipart/form-data">
			<input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
			{% for field in item_add %}

				{% if field.name == 'online_offer'%}
					<hr>
					Είναι σε προσφορά:
					<select id="id_online_offer" name="online_offer">
						<option value="--">--</option>
						<option value="True">Ναι</option>
						<option value="False">Όχι</option>
					</select>
				{% else %}
					{{field}}
				{% endif %}



			{% endfor %}
			<hr>
			<div class="form-group">
				<button type="submit" class="btn btn-success">Προσθήκη</button>
			</div>
		</form>
	</div>
</div>

{%endblock%}


{% block js_scripts %}

{% endblock %}

peripteras/templates/jinja2/kiosk-managers/item_edit.html
{% extends "manager_base.html" %}

{% block menu_conttent %}
	<li><a href="{{ url('managers:kiosk_dashboard') }}">Παραγγελίες <span class="sr-only">(current)</span></a></li>
	<li><a href="{{ url('managers:kiosk_info') }}"">Πληροφορίες περιπτέρου</a></li>
	<li><a href="{{ url('managers:all_items') }}">Προϊόντα</a></li>
	<li><a href="{{ url('managers:help') }}">Βοήθεια</a></li>
{%endblock%}




{% block main_conttent %}
<style type="text/css">

label{
	display: none;
}
input,select {
	margin-bottom: : 10px;
	margin-top: 10px;
	vertical-align: middle;
}
#id_online_offer{
	margin: 0px;
}
ul{
	list-style-type: none;
	padding: 0px;
}
.errorlist{ 
	background-color: #e64d4d;
	padding: 10px;
	color: white;
	margin-top: 5px;
}
</style>
<h1 class="page-header">Επεξεργασία προϊόντος
<div class="btn btn-danger pull-right" id="delete">Διαγραφή προϊόντος</div>
</h1>

<div class="row" >
	<div class="col-lg-4 col-md-4 col-sm-4  text-left ">
		<form method="post" action="{{ url('managers:item_edit', args=[item.id])}}" role="form" enctype="multipart/form-data">
			<input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
			{% for field in item_edit %}

				{% if field.name == 'online_offer'%}
					<hr>
					Είναι σε προσφορά:
					<select id="id_online_offer" name="online_offer">
						<option value="--">--</option>
						<option value="True">Ναι</option>
						<option value="False">Όχι</option>
					</select>
				{% else %}
					{{field}}
				{% endif %}



			{% endfor %}
			<hr>
			<div class="form-group">
				<button type="submit" class="btn btn-success">Αποθήκευση</button>
			</div>
		</form>
	</div>
</div>


<div id="confirm-delete" class="modal fade" role="dialog">
	<div class="modal-dialog ">
		<div class="modal-content">
			<div class="modal-header" id="confirm-text">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
				<div class="modal-title" id="myModalLabel">										
				<h3 >Διαγραφή προϊόντος?</h3>
				</div>
			</div>
			<div class="modal-body">
				<div class="row">
					<div class="col-lg-12 col-md-12">
						<a class="btn btn-success" href="{{ url('managers:item_delete', args=[item.id])}}">Ναι</a>
						<button class="btn btn-danger" id="cancel">
							Άκυρο
						</button>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


{%endblock%}



{% block js_scripts %}
	<script type="text/javascript">
		$(document).ready(function() {

			$( "#delete" ).click(function() {
				$('#confirm-delete').modal('show')
					
			});
			$( "#cancel" ).click(function() {
				$('#confirm-delete').modal('hide')
					
			});

		});

	</script>
{% endblock %}

peripteras/templates/jinja2/kiosk-managers/kiosk_info.html
{% extends "manager_base.html" %}

{% block menu_conttent %}
	<li><a href="{{ url('managers:kiosk_dashboard') }}">Παραγγελίες <span class="sr-only">(current)</span></a></li>
	<li class="active"><a href="{{ url('managers:kiosk_info') }}"">Πληροφορίες περιπτέρου</a></li>
	<li><a href="{{ url('managers:all_items') }}">Προϊόντα</a></li>
	<li><a href="{{ url('managers:help') }}">Βοήθεια</a></li>
{%endblock%}




{% block main_conttent %}
<style type="text/css">

/*label{
	display: none;
}*/
label{
	display: block;
	margin-bottom: 0px;
	margin-top: 10px;
	color: #565656;
} 
/*label[for="id_max_distance"]{
	display: block;
	margin-bottom: 0px;
	margin-top: 10px;
	font-weight: normal;
} */
input,textarea, select {
	margin: 0px;
	vertical-align: middle;
}

ul{
	list-style-type: none;
	padding: 0px;
}
.errorlist{ 
	background-color: #e64d4d;
	padding: 10px;
	color: white;
	margin-top: 5px;
}

#info-form p{
	background-color: #f6f6f6;
	padding: 10px;
	margin-top: 0px;
	border: 1px solid #dbdbdb;
	border-radius: 3px;
}
label[for="image-clear_id"]{
	display: inline;
}
#image-clear_id{

}

p a {
	display: block;
}

</style>
<h1 class="page-header">Επεξεργασία πληροφοριών</h1>

<div class="row" >
	<div class="col-lg-4 col-md-4 col-sm-4  text-left ">
		<form method="post" action="/kiosk/info/" role="form" id="info-form" enctype="multipart/form-data">
			<input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
			{{kiosk_info.as_p()}}
			<hr>
			<div class="form-group">
				<button type="submit" class="btn btn-success">Αποθήκευση</button>
			</div>
		</form>
	</div>
</div>

{%endblock%}


{% block js_scripts %}

{% endblock %}